[package]
name = "timonde"
version = "0.1.0"
edition = "2021"
authors = ["Ben Thibaud <b_thibaud@laposte.net>"]
description = "Lecteur de webradios ultra-léger et discret pour la barre des tâches Linux"
license = "GPL-3.0-or-later"
repository = "https://github.com/benthibaud/TiMonde"

[dependencies]
quick-xml = "0.37"
ksni = { version = "0.3.6", features = ["blocking"] }
zbus = "5"
gstreamer = "0.23"
log = "0.4"
env_logger = "0.11"
ureq = { version = "2.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libc = "0.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
